# Generated by Django 3.2.3 on 2021-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=250, unique=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('invites', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
